# -*- coding: utf-8 -*-
"""Arithmetic_Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qbfMMG1Sk-viT1mVL5Me7XbTQeLy2aQ
"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error: Division by zero is not allowed."
    return a / b

def modulo(a, b):
    if b == 0:
        return "Error: Modulo by zero is not allowed."
    return a % b